# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Gradle.gitlab-ci.yml

# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle

image: gradle:8.7-jdk17

stages:
  - build
  - staticAnalysis
  - test
  - deploy


# Default build cache settings to extend from
.build_cached:
  cache:
    key: "gradle-build"
    paths:
      - .gradle/
      - .idea/
    policy: pull-push

gradle_build:
  extends: .build_cached
  stage: build
  cache:
    policy: pull-push
  artifacts:
    name: build
    paths:
      - build/
  script:
    - gradle clean
    - gradle build testClasses  -x spotlessCheck -x test 



build-interactive-rebase-jetbrains:
  extends: .build_cached
  needs:
    - gradle_build
  dependencies:
    - gradle_build
  stage: build
  script:
    gradle assemble 


spotless-interactive-rebase-jetbrains:
  #extends: .build_cached
  needs:
    - gradle_build
  dependencies:
    - gradle_build
  stage: staticAnalysis
  script:
    gradle spotlessKotlinCheck 


PMD-interactive-rebase-jetbrains:
  #extends: .build_cached
  needs:
    - gradle_build
  dependencies:
    - gradle_build
  stage: staticAnalysis
  script:
    gradle pmdMain pmdTest

test-interactive-rebase-jetbrains:
#  extends: .build_cached
  needs:
    - gradle_build
  dependencies:
    - gradle_build
  stage: test
  script:
    - gradle test jacocoTestReport
    - cat build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/

deploy-interactive-rebase-jetbrains:
  needs:
    - gradle_build
    - build-interactive-rebase-jetbrains
    - spotless-interactive-rebase-jetbrains
    - test-interactive-rebase-jetbrains
  dependencies:
    - gradle_build
  stage: deploy
  script:
    - gradle publishPlugin
  only:
    - main